<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoginEmail Username No TeleponPasswordB_369523</name>
   <tag></tag>
   <elementGuidId>25be5de4-bcf3-4fd9-bcd8-07fb23480304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginEmail/ Username/ No TeleponPasswordBelum dapat link aktivasi? Klik Disini Anda Belum Melakukan Demo Account. Silahkan Melakukan demo terlebih dahulu. Klik Link Berikut !LoginLupa Password?</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrap-content&quot;]/div[@class=&quot;hello&quot;]/div[@class=&quot;content-right&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginEmail/ Username/ No TeleponPasswordBelum dapat link aktivasi? Klik Disini Anda Belum Melakukan Demo Account. Silahkan Melakukan demo terlebih dahulu. Klik Link Berikut !LoginLupa Password?' or . = 'LoginEmail/ Username/ No TeleponPasswordBelum dapat link aktivasi? Klik Disini Anda Belum Melakukan Demo Account. Silahkan Melakukan demo terlebih dahulu. Klik Link Berikut !LoginLupa Password?')]</value>
   </webElementXpaths>
</WebElementEntity>
